In [7]:
!pip install scikit-learn


     ---------------------------------------- 9.3/9.3 MB 3.2 MB/s eta 0:00:00
     -------------------------------------- 302.2/302.2 KB 2.7 MB/s eta 0:00:00
     ---------------------------------------- 44.1/44.1 MB 1.5 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\imjo6\OneDrive\Desktop\P_301\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [59]:
import numpy as np
import pandas as pd
import seaborn as sns
import pickle
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [12]:
data=pd.read_excel('bank_p301.xlsx')

In [13]:
data

industrial_risk   management_risk   financial_flexibility   credibility  \
0                0.5               1.0                     0.0           0.0   
1                0.0               1.0                     0.0           0.0   
2                1.0               0.0                     0.0           0.0   
3                0.5               0.0                     0.0           0.5   
4                1.0               1.0                     0.0           0.0   
..               ...               ...                     ...           ...   
245              0.0               1.0                     1.0           1.0   
246              1.0               1.0                     0.5           1.0   
247              0.0               1.0                     1.0           0.5   
248              1.0               0.0                     0.5           1.0   
249              1.0               0.0                     0.5           0.5   

      competitiveness   operating_risk           class  
0                 0.0              0.5      bankruptcy  
1                 0.0              1.0      bankruptcy  
2                 0.0              1.0      bankruptcy  
3                 0.0              1.0      bankruptcy  
4                 0.0              1.0      bankruptcy  
..                ...              ...             ...  
245               1.0              1.0  non-bankruptcy  
246               1.0              0.0  non-bankruptcy  
247               0.5              0.0  non-bankruptcy  
248               0.5              0.0  non-bankruptcy  
249               1.0              1.0  non-bankruptcy  

[250 rows x 7 columns]

**EXPLORATORY DATA ANALYSIS**

In [14]:
data.columns

Index(['industrial_risk', ' management_risk', ' financial_flexibility',
       ' credibility', ' competitiveness', ' operating_risk', ' class'],
      dtype='object')

In [15]:
data.isnull().any()

industrial_risk           False
 management_risk          False
 financial_flexibility    False
 credibility              False
 competitiveness          False
 operating_risk           False
 class                    False
dtype: bool

In [16]:
data.isnull().sum()

industrial_risk           0
 management_risk          0
 financial_flexibility    0
 credibility              0
 competitiveness          0
 operating_risk           0
 class                    0
dtype: int64

In [18]:
data.dtypes

industrial_risk           float64
 management_risk          float64
 financial_flexibility    float64
 credibility              float64
 competitiveness          float64
 operating_risk           float64
 class                     object
dtype: object

In [19]:
data.describe().style.background_gradient(cmap='Accent_r')

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data[' class']=le.fit_transform(data[' class'])
data

industrial_risk   management_risk   financial_flexibility   credibility  \
0                0.5               1.0                     0.0           0.0   
1                0.0               1.0                     0.0           0.0   
2                1.0               0.0                     0.0           0.0   
3                0.5               0.0                     0.0           0.5   
4                1.0               1.0                     0.0           0.0   
..               ...               ...                     ...           ...   
245              0.0               1.0                     1.0           1.0   
246              1.0               1.0                     0.5           1.0   
247              0.0               1.0                     1.0           0.5   
248              1.0               0.0                     0.5           1.0   
249              1.0               0.0                     0.5           0.5   

      competitiveness   operating_risk   class  
0                 0.0              0.5       0  
1                 0.0              1.0       0  
2                 0.0              1.0       0  
3                 0.0              1.0       0  
4                 0.0              1.0       0  
..                ...              ...     ...  
245               1.0              1.0       1  
246               1.0              0.0       1  
247               0.5              0.0       1  
248               0.5              0.0       1  
249               1.0              1.0       1  

[250 rows x 7 columns]

In [25]:
corr=data.corr()
corr

industrial_risk   management_risk  \
industrial_risk                1.000000          0.255127   
 management_risk               0.255127          1.000000   
 financial_flexibility        -0.162624         -0.254845   
 credibility                  -0.014438         -0.303341   
 competitiveness              -0.257814         -0.306568   
 operating_risk                0.144507          0.213874   
 class                        -0.227823         -0.370838   

                         financial_flexibility   credibility  \
industrial_risk                      -0.162624     -0.014438   
 management_risk                     -0.254845     -0.303341   
 financial_flexibility                1.000000      0.524951   
 credibility                          0.524951      1.000000   
 competitiveness                      0.686612      0.675689   
 operating_risk                      -0.116903     -0.288458   
 class                                0.751020      0.755909   

                         competitiveness   operating_risk     class  
industrial_risk                -0.257814         0.144507 -0.227823  
 management_risk               -0.306568         0.213874 -0.370838  
 financial_flexibility          0.686612        -0.116903  0.751020  
 credibility                    0.675689        -0.288458  0.755909  
 competitiveness                1.000000        -0.211383  0.899452  
 operating_risk                -0.211383         1.000000 -0.279786  
 class                          0.899452        -0.279786  1.000000

In [26]:
data[' management_risk'].unique()

array([1. , 0. , 0.5])

In [27]:
data[' class'].unique()

array([0, 1])

In [28]:
data[' competitiveness'].unique()

array([0. , 0.5, 1. ])

In [29]:
data['industrial_risk'].unique()

array([0.5, 0. , 1. ])

In [30]:
data[' financial_flexibility'].unique()

array([0. , 0.5, 1. ])

In [31]:
data[' operating_risk'].unique()

array([0.5, 1. , 0. ])

In [32]:
data[' credibility'].unique()

array([0. , 0.5, 1. ])

In [38]:
x = data.iloc[:,0:6]
x

industrial_risk   management_risk   financial_flexibility   credibility  \
0                0.5               1.0                     0.0           0.0   
1                0.0               1.0                     0.0           0.0   
2                1.0               0.0                     0.0           0.0   
3                0.5               0.0                     0.0           0.5   
4                1.0               1.0                     0.0           0.0   
..               ...               ...                     ...           ...   
245              0.0               1.0                     1.0           1.0   
246              1.0               1.0                     0.5           1.0   
247              0.0               1.0                     1.0           0.5   
248              1.0               0.0                     0.5           1.0   
249              1.0               0.0                     0.5           0.5   

      competitiveness   operating_risk  
0                 0.0              0.5  
1                 0.0              1.0  
2                 0.0              1.0  
3                 0.0              1.0  
4                 0.0              1.0  
..                ...              ...  
245               1.0              1.0  
246               1.0              0.0  
247               0.5              0.0  
248               0.5              0.0  
249               1.0              1.0  

[250 rows x 6 columns]

In [39]:
y=data.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
245    1
246    1
247    1
248    1
249    1
Name:  class, Length: 250, dtype: int32

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=200) 

In [43]:
regressor=LogisticRegression()
regressor.fit(x_train,y_train)

LogisticRegression()

In [61]:
class_predictions=regressor.predict(x_test)
class_predictions

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1])

In [62]:
actual_vs_prediction=pd.DataFrame({'Actual':y_test,'Predictions':class_predictions})
actual_vs_prediction

Actual  Predictions
145       1            1
200       1            1
22        0            0
192       1            1
204       1            1
154       1            1
91        0            0
240       1            1
39        0            0
144       1            1
58        0            0
165       1            1
12        0            0
182       1            1
127       1            1
142       1            1
102       0            0
9         0            0
100       0            0
163       1            1
210       1            1
69        0            0
166       1            1
230       1            1
49        0            0
232       1            1
208       1            1
136       1            1
44        0            0
179       1            1
203       1            1
74        0            0
215       1            1
226       1            1
75        0            0
94        0            0
174       1            1
41        0            0
40        0            0
96        0            0
147       1            1
5         0            0
19        0            0
32        0            0
207       1            1
171       1            1
115       1            1
235       1            1
18        0            0
225       1            1

In [63]:
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score

In [65]:
confusion_matrix(y_test,class_predictions)

array([[21,  0],
       [ 0, 29]], dtype=int64)

In [68]:
accuracy_score(y_test,class_predictions)

1.0

In [69]:
from sklearn.model_selection import GridSearchCV
parameters={'penalty':['l1','l2','elasticnet'],'C':[1,2,3,4,5,10,20,30,40,50],'max_iter':[100,200,300]}

In [50]:
regressor_regression=GridSearchCV(regressor,param_grid=parameters,scoring='accuracy',cv=5)

In [51]:
import warnings
warnings.filterwarnings("ignore")

In [52]:
regressor_regression.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 10, 20, 30, 40, 50],
                         'max_iter': [100, 200, 300],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [53]:
print(regressor_regression.best_params_)

{'C': 1, 'max_iter': 100, 'penalty': 'l2'}


In [54]:
print(regressor_regression.best_score_)

0.9949999999999999


In [55]:
y_pred_test=regressor_regression.predict(x_test)

In [56]:
y_pred_test

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1])

In [57]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_pred_test,y_test)

1.0

In [58]:
print(classification_report(y_pred_test,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        29

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



In [ ]:
with open('model.pkl','wb') as files:
    pickle.dump(regressor,files)